security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 4

    enable_authenticator_manager: true

    # Proveedores de usuarios
    providers:
        proveedor:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: proveedor
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login

    # Control de acceso
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4 # Valor más bajo posible para bcrypt
                time_cost: 3 # Valor más bajo posible para argon
                memory_cost: 10 # Valor más bajo posible para argon

        access_control:
        
